// Fix: Added maxWidth: { 'container-max': '1280px' }
// The original had container-max only in `spacing`, but Tailwind's max-w-* utilities
// read from theme.maxWidth, not theme.spacing — so max-w-container-max generated nothing.

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-lowest": "#0e0e0e",
        "surface": "#131313",
        "primary-fixed-dim": "#c0c1ff",
        "on-surface": "#e5e2e1",
        "on-tertiary-fixed": "#3e0022",
        "on-surface-variant": "#c7c4d7",
        "inverse-on-surface": "#313030",
        "primary-container": "#8083ff",
        "on-tertiary-fixed-variant": "#8c0053",
        "tertiary-fixed-dim": "#ffb0cd",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-container-high": "#2a2a2a",
        "on-error-container": "#ffdad6",
        "surface-bright": "#3a3939",
        "on-primary": "#1000a9",
        "on-secondary-container": "#d6a9ff",
        "outline-variant": "#464554",
        "tertiary-fixed": "#ffd9e4",
        "surface-container-highest": "#353534",
        "on-secondary-fixed-variant": "#6900b3",
        "secondary-fixed-dim": "#ddb7ff",
        "background": "#131313",
        "secondary-container": "#6f00be",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#2c0051",
        "primary": "#c0c1ff",
        "surface-tint": "#c0c1ff",
        "surface-dim": "#131313",
        "error-container": "#93000a",
        "tertiary-container": "#f751a1",
        "inverse-primary": "#494bd6",
        "on-primary-container": "#0d0096",
        "surface-variant": "#353534",
        "primary-fixed": "#e1e0ff",
        "on-error": "#690005",
        "on-primary-fixed": "#07006c",
        "on-secondary": "#490080",
        "secondary-fixed": "#f0dbff",
        "tertiary": "#ffb0cd",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-container": "#570032",
        "outline": "#908fa0",
        "secondary": "#ddb7ff",
        "on-tertiary": "#640039",
        "on-background": "#e5e2e1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "section-gap": "96px",
        gutter: "24px",
      },
      // Fix: moved container-max to maxWidth so max-w-container-max actually works
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "body-lg": ["Geist", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-md": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
